os: Visual Studio 2017
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
  - ps: ./build.ps1
test: off
branches:
  only:
    - master
    - develop
    - appveyor
artifacts:
  - path: 'artifacts\*.nupkg'
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: VFNEM1Py3Wavrd8I9eOWquMkcJnjgQzesKEFwd8+n0ZwbuDDbZexUaYJSQAzXND4
  on:
    appveyor_repo_tag: true

# Workaround http://status.appveyor.com/incidents/m2vdvw39kdk8
hosts:
  api.nuget.org: 93.184.221.200

